apiVersion: v1
kind: ConfigMap
metadata:
  name: iconics-modbus-simulator-backend-${IMAGE_TAG}
  namespace: scada-grita
data:
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "${FASTAPI_PORT}"
  MODBUS_HOST: "0.0.0.0"
  MODBUS_PORT: "${MODBUS_PORT}"