apiVersion: v1
kind: ConfigMap
metadata:
  name: iconics-modbus-simulator-backend
  namespace: scada-grita
data:
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "7501"
  MODBUS_HOST: "0.0.0.0"
  MODBUS_PORT: "9001"