apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-simulator-backend-${IMAGE_TAG}
  namespace: scada-grita
  labels:
    app: modbus-simulator-backend-${IMAGE_TAG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus-simulator-backend-${IMAGE_TAG}
  template:
    metadata:
      labels:
        app: modbus-simulator-backend-${IMAGE_TAG}
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: modbus-simulator-backend-${IMAGE_TAG}
          image: 10.14.73.59/scada/modbus-simulator-backend-${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: ${FASTAPI_PORT}
            - containerPort: ${MODBUS_PORT}
          envFrom:
            - configMapRef:
                name: modbus-simulator-backend-${IMAGE_TAG}
          volumeMounts:
            - name: modbus-simulator-backend-${IMAGE_TAG}-config
              mountPath: /app/config
      volumes:
        - name: modbus-simulator-backend-${IMAGE_TAG}-config
          configMap:
            name: modbus-simulator-backend-${IMAGE_TAG}

---
apiVersion: v1
kind: Service
metadata:
  name: modbus-simulator-backend-${IMAGE_TAG}-service
  namespace: scada-grita
  labels:
    app: modbus-simulator-backend-${IMAGE_TAG}
spec:
  type: NodePort
  selector:
    app: modbus-simulator-backend-${IMAGE_TAG}
  ports:
    - name: fastapi-port
      port: ${FASTAPI_PORT}
      targetPort: ${FASTAPI_PORT}
      nodePort: ${FASTAPI_NODEPORT}
      protocol: TCP
    - name: modbus-port
      port: ${MODBUS_PORT}
      targetPort: ${MODBUS_PORT}
      nodePort: ${MODBUS_NODEPORT}
      protocol: TCP