apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-simulator-backend
  namespace: scada-grita
  labels:
    app: modbus-simulator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus-simulator-backend
  template:
    metadata:
      labels:
        app: modbus-simulator-backend
    spec:
      containers:
        - name: modbus-simulator-backend
          image: 10.14.73.59/scada/modbus-simulator-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 7501
            - containerPort: 9001
          envFrom:
            - configMapRef:
                name: iconics-modbus-simulator-backend
          volumeMounts:
            - name: backend-config
              mountPath: /app/config
      volumes:
        - name: backend-config
          configMap:
            name: iconics-modbus-simulator-backend

---
apiVersion: v1
kind: Service
metadata:
  name: modbus-simulator-backend-service
  namespace: scada-grita
  labels:
    app: modbus-simulator-backend
spec:
  type: NodePort
  selector:
    app: modbus-simulator-backend
  ports:
    - name: fastapi-port
      port: 7501
      targetPort: 7501
      nodePort: 30501
      protocol: TCP
    - name: modbus-port
      port: 9001
      targetPort: 9001
      nodePort: 30901
      protocol: TCP