services:
  backend_modbus_tcp_server_simulator:
    build: ./backend
    ports:
      - "7501:7501"
      - "8001:8001"
    networks:
      - app-tier
    env_file:
      - ./backend/.env
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=7501
      - MODBUS_HOST=0.0.0.0
      - MODBUS_PORT=8001

  frontend_modbus_tcp_server_simulator:
    build: ./frontend
    ports:
      - "3001:3001"
    networks:
      - app-tier
    env_file:
      - ./frontend/.env
    environment:
      - REACT_PORT=3001
      - FASTAPI_HOST=localhost # IP address of the backend_modbus_tcp_server_simulator_1
      - FASTAPI_PORT=7501

  # backend_modbus_tcp_server_simulator_2:
  #   build: ./backend
  #   container_name: backend_modbus_tcp_server_simulator_2
  #   hostname: backend_modbus_tcp_server_simulator_2
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - app-tier
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - PORT=8002

  # frontend_modbus_tcp_server_simulator_2:
  #   build: ./frontend
  #   container_name: frontend_modbus_tcp_server_simulator_2
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - backend_modbus_tcp_server_simulator_2

  # backend_modbus_tcp_server_simulator_3:
  #   build: ./backend
  #   container_name: backend_modbus_tcp_server_simulator_3
  #   hostname: backend_modbus_tcp_server_simulator_3
  #   ports:
  #     - "8003:8003"
  #   networks:
  #     - app-tier
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - PORT=8003

  # frontend_modbus_tcp_server_simulator_3:
  #   build: ./frontend
  #   container_name: frontend_modbus_tcp_server_simulator_3
  #   ports:
  #     - "3003:3003"
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - backend_modbus_tcp_server_simulator_3

networks:
  app-tier:
    external: true