services:
  simulator_modbus_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: modbus_backend_simulator
    hostname: modbus_backend_simulator
    ports:
      - "7501:7501"
      - "9001:9001"
    env_file:
      - ./backend/.env
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=7501
      - MODBUS_HOST=0.0.0.0
      - MODBUS_PORT=9001

  simulator_modbus_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: modbus_frontend_simulator
    hostname: modbus_frontend_simulator
    ports:
      - "3005:3005"
    # networks:
    #   - app-tier
    env_file:
      - ./frontend/.env
    environment:
      - REACT_PORT=3005
      - FASTAPI_HOST=localhost # IP address of the backend_modbus_tcp_server_simulator_1
      - FASTAPI_PORT=7501