apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-modbus-simulator
  namespace: scada-grita
  labels:
    app: frontend-modbus-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-modbus-simulator
  template:
    metadata:
      labels:
        app: frontend-modbus-simulator
    spec:
      containers:
        - name: frontend-modbus-simulator
          image: 10.14.73.59/scada/frontend-modbus-simulator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: iconics-modbus-simulator-frontend
      volumes:
        - name: frontend-config
          configMap:
            name: iconics-modbus-simulator-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-modbus-simulator-service
  namespace: scada-grita
  labels:
    app: frontend-modbus-simulator
spec:
  type: NodePort
  selector:
    app: frontend-modbus-simulator
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005
      protocol: TCP