apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-simulator-frontend-${IMAGE_TAG}
  namespace: scada-grita
  labels:
    app: modbus-simulator-frontend-${IMAGE_TAG}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus-simulator-frontend-${IMAGE_TAG}
  template:
    metadata:
      labels:
        app: modbus-simulator-frontend-${IMAGE_TAG}
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: modbus-simulator-frontend-${IMAGE_TAG}
          image: 10.14.73.59/scada/modbus-simulator-frontend-${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: iconics-modbus-simulator-frontend-${IMAGE_TAG}
      volumes:
        - name: frontend-${IMAGE_TAG}-config
          configMap:
            name: iconics-modbus-simulator-frontend-${IMAGE_TAG}

---
apiVersion: v1
kind: Service
metadata:
  name: modbus-simulator-frontend-${IMAGE_TAG}-service
  namespace: scada-grita
  labels:
    app: modbus-simulator-frontend-${IMAGE_TAG}
spec:
  type: NodePort
  selector:
    app: modbus-simulator-frontend-${IMAGE_TAG}
  ports:
    - port: ${REACT_PORT}
      targetPort: ${REACT_PORT}
      nodePort: ${REACT_NODEPORT}
      protocol: TCP