apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbus-simulator-frontend
  namespace: scada-grita
  labels:
    app: modbus-simulator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modbus-simulator-frontend
  template:
    metadata:
      labels:
        app: modbus-simulator-frontend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: modbus-simulator-frontend
          image: 10.14.73.59/scada/modbus-simulator-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: iconics-modbus-simulator-frontend
      volumes:
        - name: frontend-config
          configMap:
            name: iconics-modbus-simulator-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: modbus-simulator-frontend-service
  namespace: scada-grita
  labels:
    app: modbus-simulator-frontend
spec:
  type: NodePort
  selector:
    app: modbus-simulator-frontend
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005
      protocol: TCP